[framework]
name = "spring"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Micro"
platform = "Servlet"
webserver = "Undertow"
versus = ""

[jpa]
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "Postgres"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Servlet"
webserver = "Undertow"
versus = "spring"

[mongo]
database_uri = "mongodb://tfb-database:27017/hello_world?maxPoolSize=512&minPoolSize=128"
urls.db = "/db"
urls.query = "/queries?queries="
urls.update = "/updates?queries="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Fullstack"
database = "mongodb"
database_os = "Linux"
os = "Linux"
orm = "Full"
platform = "Servlet"
webserver = "Undertow"
versus = "spring"
